//! Generated by Ply -- do not edit. Kani proof harness for `tiered_fee`
//! (check bounded(2)). See The-Ply-Spec.md D2 and §5.4b.
//!
//! (Hand-transcribed for this spike in the exact shape
//! `generate_proof_module` emits: the `use super::*`, the stub fn that
//! `kani::any()`s a return and `kani::assume`s the declared `ensures`, the
//! `#[kani::proof_for_contract]` + `#[kani::stub]` attribute pair, and the
//! `ply_stub_` / `ply_proof_` names.)
#[cfg(kani)]
use super::*;

#[cfg(kani)]
#[allow(dead_code, unused_variables)]
fn ply_stub_legacy_rate(tier: u8) -> u32 {
    let __ply_result: u32 = kani::any();
    kani::assume((|result: &u32| *result <= 10_000)(&__ply_result));
    __ply_result
}

#[cfg(kani)]
#[kani::proof_for_contract(tiered_fee)]
#[kani::stub(legacy_rate, ply_stub_legacy_rate)]
fn ply_proof_tiered_fee() {
    let amount_cents: u32 = kani::any();
    let tier: u8 = kani::any();
    tiered_fee(amount_cents, tier);
}

#[cfg(kani)]
#[kani::proof_for_contract(tiered_fee_halfclaim)]
#[kani::stub(legacy_rate, ply_stub_legacy_rate)]
fn ply_proof_tiered_fee_halfclaim() {
    let amount_cents: u32 = kani::any();
    let tier: u8 = kani::any();
    tiered_fee_halfclaim(amount_cents, tier);
}
