//! Generated proof source is scratch, even though serial Kani needs to see
//! it inside the crate. A later run must also clean output left by an older
//! Ply version after the claim or its signature changes.

use ply_e2e::{build_cargo_ply, copy_fixture, run_verify};

#[test]
fn verify_prunes_an_old_proof_module_when_no_bounded_check_remains() {
    let cargo_ply = build_cargo_ply();
    let fixture = copy_fixture("emptychecks");
    let yaml = std::fs::read_to_string(fixture.path().join("ply.yaml")).unwrap();
    std::fs::write(
        fixture.path().join("ply.yaml"),
        yaml.replace(
            "left_to_the_default: {}",
            "left_to_the_default:\n        checks: []",
        ),
    )
    .unwrap();

    let original_lib = fixture.read_lib_rs();
    fixture.write_lib_rs(&format!(
        "{original_lib}\n// Ply-generated module declaration -- do not edit this line.\nmod ply_generated;\n"
    ));
    std::fs::write(
        fixture.path().join("src/ply_generated.rs"),
        "//! Generated by Ply -- do not edit. Kani proof harness for `old_signature`\n",
    )
    .unwrap();

    let run = run_verify(&cargo_ply, fixture.path(), 30);
    assert_eq!(
        run.exit_code,
        Some(1),
        "the unchecked claims remain visible: {}",
        run.json
    );
    assert_eq!(fixture.read_lib_rs(), original_lib);
    assert!(!fixture.path().join("src/ply_generated.rs").exists());
}
