//! Generated by Ply -- do not edit. Kani proof harness for `vec_sum`
//! (check bounded(8)). See The-Ply-Spec.md D2 and §5.4b.
#[cfg(kani)]
use super::*;

#[cfg(kani)]
#[kani::proof_for_contract(vec_sum)]
#[kani::unwind(9)]
fn ply_proof_vec_sum() {
    let v = kani::vec::any_vec::<u8, 8>();
    vec_sum(&v);
}
