// Generated by Ply's composition adapter. Every obligation below is
// entailment from contracts: no function bodies appear, and none are read.
// THE SATISFIABILITY PROBES. Each asks the solver to derive a falsehood from one
         // contract alone. Expected result: an error for EVERY obligation below. One that
         // verifies is a contract that contradicts itself, and every other answer about
         // that operation means nothing.
#![allow(non_snake_case)]
use vstd::prelude::*;

verus! {

/// The readings the property is written in terms of.
pub struct S {
    pub available: int,
    pub capacity: int,
}

/// The declared Rust widths, carried as premises rather than assumed. A
/// reading modelled as an *unbounded* integer is a different program.
pub open spec fn typed(s: S) -> bool {
    true
    && 0 <= s.available <= 4294967295
    && 0 <= s.capacity <= 4294967295
}

pub open spec fn inv(s: S) -> bool { s.available <= s.capacity }

/// The contract of `TokenBucket::new`, exactly as it was proved.
pub open spec fn TokenBucket_new_post(post: S, cap: int) -> bool {
    true
    && (post.available == cap)
    && (post.capacity == cap)
}

/// The contract of `TokenBucket::refill`, exactly as it was proved.
pub open spec fn TokenBucket_refill_post(pre: S, post: S, tokens: int) -> bool {
    true
    && (post.available == (if (if pre.available + tokens < 0 { 0 } else if pre.available + tokens > 4294967295 { 4294967295 } else { pre.available + tokens }) <= pre.capacity { (if pre.available + tokens < 0 { 0 } else if pre.available + tokens > 4294967295 { 4294967295 } else { pre.available + tokens }) } else { pre.capacity }))
    && (post.capacity == pre.capacity)
}

/// The contract of `TokenBucket::try_take`, exactly as it was proved.
pub open spec fn TokenBucket_try_take_post(pre: S, post: S, tokens: int, ok: bool) -> bool {
    true
    && (ok == (pre.available >= tokens))
    && ((ok) ==> (post.available == pre.available - tokens))
    && ((!ok) ==> (post.available == pre.available))
    && (post.capacity == pre.capacity)
}

/// The part of `TokenBucket::try_take`'s contract that says nothing about the state after.
/// The range obligation may assume this and nothing else: a clause about the
/// state after can restate what the declared type already guarantees, which
/// hands back the premise that obligation exists to withhold.
pub open spec fn TokenBucket_try_take_before(pre: S, tokens: int, ok: bool) -> bool {
    true
    && (ok == (pre.available >= tokens))
}

/// VERIFYING THIS IS THE FAILURE. A contract that contradicts itself
/// entails everything, including its own invariant, so a green result
/// elsewhere would mean nothing. This asks the solver for a falsehood from
/// the contract alone: it must NOT be able to find one. (One-sided -- it
/// detects a contradiction, it does not certify there is none.)
proof fn ob_reach_TokenBucket_try_take(pre: S, post: S, tokens: int, ok: bool)
    requires
        inv(pre),
        typed(pre),
        typed(post),
        0 <= tokens <= 4294967295,
        TokenBucket_try_take_post(pre, post, tokens, ok),
    ensures false
{ }

/// VERIFYING THIS IS THE FAILURE. A contract that contradicts itself
/// entails everything, including its own invariant, so a green result
/// elsewhere would mean nothing. This asks the solver for a falsehood from
/// the contract alone: it must NOT be able to find one. (One-sided -- it
/// detects a contradiction, it does not certify there is none.)
proof fn ob_reach_TokenBucket_refill(pre: S, post: S, tokens: int)
    requires
        inv(pre),
        typed(pre),
        typed(post),
        0 <= tokens <= 4294967295,
        TokenBucket_refill_post(pre, post, tokens),
    ensures false
{ }

fn main() { }
}
