//! `cargo ply audit` (§6): "trust surface: profile escapes, assumed
//! contracts, derived fns".
//!
//! **The trust surface is everything this codebase's evidence rests on that
//! Ply itself never checked.** Six kinds of thing land on it, and every one
//! of them is a decision somebody made on purpose:
//!
//! - **assumed contracts** (§5.5) — a `bounded` proof that replaced a
//!   callee with the promise `ply.yaml` declares for it. The caller's
//!   verdict reads `conditional`, and the assumption carries
//!   `owed-evidence` until something runs the real callee against the
//!   promise. Until this command existed, `owed-evidence` was recorded
//!   nowhere and displayed nowhere: §5.5 described `audit` listing it in
//!   the present tense while nothing listed anything.
//! - **environmental assumptions** (§5.1) — an `entry:` fn's own
//!   `requires`, which the outside world is trusted to satisfy.
//! - **trusted claims** (§5.4d) — a human's attestation, with its evidence.
//! - **helpers called from contracts** (§5.4a) — a contract is only as true
//!   as what it calls.
//! - **profile escapes** (§5.3) — `#[ply::allow(...)]`, an exemption
//!   granted once and easy to forget.
//! - **derived bodies** (§5.7) — code a model wrote against its own spec.
//!
//! Listing them is not an accusation, and this command never fails a run
//! for having them: `conditional` is the *normal* state of a
//! legacy-extension codebase (§5.5), and a tool that reported honest
//! declarations as failures would teach people to stop writing them. What
//! is *owed* — and expected to close — is `cargo ply worklist`.
//!
//! No engines start here, so `audit` produces no verdicts. Every node in
//! its envelope reads `unclaimed`.

use std::collections::BTreeSet;
use std::path::Path;

use anyhow::Result;
use ply_core::diag::{Coverage, Envelope, Tier, TrustItem};
use ply_core::harness;
use ply_core::model::Mode;
use ply_core::surface::{self, SourceSurface};

use crate::shared::{
    self, Loaded, empty_workspace, load_document, local_anchor_names, walk_fn_claims,
    workspace_node, wrap,
};

const PLY_VERSION: &str = env!("CARGO_PKG_VERSION");

/// What `audit` cannot look at, in the words a user needs to know what this
/// list leaves out. Exact strings, tested as such: the honesty of a short
/// trust surface is carried entirely by these five sentences.
const ATTESTATION_GAP: &str = "NOT CHECKED. §5.4d says an attestation stops covering an item \
     once that item changes, and that `audit` then lists it as owed re-attestation. Ply does \
     record a hash of what it checks, but only for claims it checked itself — an attestation is a \
     person's word, nothing runs for it, and no hash of the item it vouches for is kept. So every \
     attestation above is listed with no coverage state at all, and one signed off against a \
     function that has since been rewritten looks exactly like one signed off this morning.";
const DISCHARGE_GAP: &str = "NOT CHECKED. An assumed contract stops being owed once something \
     runs the real callee against the promise. This command starts no engines and does not read \
     the results `cargo ply verify` records, so every assumption above is reported as owed — \
     including one whose callee declares a check that has been passing for months. `cargo ply \
     verify` is what exercises it.";
const HELPER_GAP: &str = "NOT CHECKED. §5.4a says a helper used in a contract that does not \
     itself carry a passing check makes every verdict built on it `conditional`. This list says \
     which helpers a contract trusts; it never says whether they earned that trust, because that \
     is a verdict and this command produces none.";
const CALL_SITE_GAP: &str = "NOT CHECKED. Ply finds assumed contracts by reading the call sites \
     written in a claimed function's own body. Calls it cannot see are not on this list: calls \
     generated by a macro, made through a function pointer or a trait method, or written inside a \
     callee rather than in the claim itself. An assumption reached that way is just as real and \
     is not listed here (§5.5).";
const ARCHITECTURE_GAP: &str = "NOT CHECKED. A `#[ply::allow(...)]` escape switches off an \
     architecture finding, and the architecture tier is M2 — nothing in this build reports those \
     findings in the first place. Each escape above is listed as the declaration it is; none of \
     them is currently turning anything off.";

/// What a clean surface means, so an empty list cannot be read as "verified".
const EMPTY_SURFACE: &str = "Nothing in this crate rests on trust that Ply can see: no assumed \
     contract, no attestation, no escape, no derived body, and no contract that calls a helper. \
     That is a fact about what is declared, not a verdict about the code — see what this command \
     could not look at, below.";

/// The sentence that stops a short `audit` from reading like a verified
/// codebase, and the one that keeps `audit` and `worklist` apart.
const NO_VERDICTS: &str = "`audit` runs no engines, so it produces no verdicts: every claim in \
     this run's `--json` envelope reads `unclaimed` because this command gathered no evidence \
     about it, not because the code is unverified. A trust surface is not a list of defects — \
     each line is something somebody decided on purpose, listed so the decision stays visible. \
     `cargo ply verify` is what produces verdicts; `cargo ply worklist` is what lists the things \
     that are owed.";

#[derive(Debug)]
pub struct AuditReport {
    pub envelope: Envelope,
    /// The `ply.yaml` this run read, for the human header.
    pub document: String,
}

impl AuditReport {
    /// The tiers, in the order they are reported. Fixed, so two runs on a
    /// growing codebase read as the same document with more lines in it.
    pub const TIERS: [&'static str; 6] = [
        "assumed_contract",
        "environmental_assumption",
        "trusted_claim",
        "contract_helper",
        "profile_escape",
        "derived_fn",
    ];

    /// §6's exit codes: 0 clean, 1 any error-severity finding (which for
    /// this command means a document that will not load), 2 tool error
    /// (an `Err` out of [`audit_crate`]).
    ///
    /// **A trust surface never fails the run.** An assumption, an
    /// attestation and an escape are all things a user wrote deliberately;
    /// exiting non-zero for them would push people to delete honest
    /// declarations, which is the one outcome this command must not cause.
    pub fn exit_code(&self) -> i32 {
        if self
            .envelope
            .diagnostics
            .iter()
            .any(|d| d.severity == "error")
        {
            1
        } else {
            0
        }
    }
}

/// How one item relates to the node beside it, in the words the tier
/// means: an assumption is *assumed by* a caller, an escape is *declared
/// on* an item. "node_id" is a field name, not a sentence.
fn relation(kind: &str) -> &'static str {
    match kind {
        "assumed_contract" => "assumed by",
        "environmental_assumption" => "assumed on entry to",
        "trusted_claim" => "attested on",
        "contract_helper" => "trusted by the contract on",
        "profile_escape" => "declared on",
        "derived_fn" => "the body of",
        _ => "on",
    }
}

/// The one line a reader scans before deciding whether to read the
/// paragraph under it.
fn item_line(item: &TrustItem) -> String {
    let at = match &item.where_ {
        Some(w) => format!(" (at {w})"),
        None => String::new(),
    };
    let statuses = if item.statuses.is_empty() {
        String::new()
    } else {
        format!("  [{}]", item.statuses.join(", "))
    };
    format!(
        "`{}` — {} `{}`{at}{statuses}",
        item.subject,
        relation(&item.kind),
        item.node_id
    )
}

/// The human name of one tier, for the printed report.
fn tier_heading(kind: &str) -> String {
    match kind {
        "assumed_contract" => "assumed contracts",
        "environmental_assumption" => "environmental assumptions",
        "trusted_claim" => "trusted claims",
        "contract_helper" => "helpers called from contracts",
        "profile_escape" => "profile escapes",
        "derived_fn" => "derived bodies",
        other => other,
    }
    .to_string()
}

pub fn audit_crate(crate_dir: &Path) -> Result<AuditReport> {
    let yaml_path = crate_dir.join("ply.yaml");
    let document = yaml_path.display().to_string();

    let doc = match load_document(&yaml_path, "audit")? {
        Loaded::Document(doc) => *doc,
        Loaded::SchemaViolations(violations) => {
            return Ok(AuditReport {
                envelope: Envelope {
                    command: "audit".into(),
                    ply_version: PLY_VERSION.into(),
                    root: empty_workspace(),
                    diagnostics: violations,
                    coverage: Some(unread_coverage()),
                    // Absent, not empty: this run did not read a trust
                    // surface, which is a different fact from reading one
                    // and finding nothing.
                    trust_surface: None,
                    open_items: None,
                    not_carried_forward: vec![],
                },
                document,
            });
        }
    };

    let local_anchors = local_anchor_names(crate_dir);
    let scanned = surface::scan_crate(crate_dir);
    let lib_path = crate_dir.join("src/lib.rs");

    let mut items: Vec<TrustItem> = Vec::new();
    let mut claims = 0usize;
    let mut derived_claimed: BTreeSet<String> = BTreeSet::new();

    walk_fn_claims(&doc, |c| {
        claims += 1;
        let node_id = c.node_id();
        let local = shared::is_local(&local_anchors, c.anchor);
        let cf = if local {
            harness::discover_fn(&lib_path, c.fn_name).ok()
        } else {
            None
        };

        // §5.1: an `entry:` fn's own preconditions are assumptions about the
        // world outside. Deduplicated across the two places a contract can
        // be written, since one clause written twice is still one assumption.
        if !c.claim.entry.is_empty() {
            // The document's spelling wins: it is what the user typed,
            // while the inline attribute comes back from the parser
            // token-spaced (`bps_ok (bps)`). Comparing the raw strings
            // listed one assumption twice.
            let mut clauses: Vec<String> = c.claim.requires.clone();
            if let Some(cf) = cf.as_ref()
                && let Some((_, text)) = &cf.requires
                && !clauses.iter().any(|r| surface::same_expression(r, text))
            {
                clauses.push(text.clone());
            }
            for clause in clauses {
                items.push(environmental_assumption_item(
                    &node_id,
                    c.fn_name,
                    &clause,
                    &c.claim.entry,
                ));
            }
        }

        for t in &c.claim.trusted {
            items.push(trusted_claim_item(
                &node_id,
                c.fn_name,
                &t.claim,
                &t.evidence,
            ));
        }

        // §5.4a: every helper a contract calls, from both places a contract
        // can be written.
        let mut helpers: Vec<String> = Vec::new();
        let mut contract_sources: Vec<String> = Vec::new();
        contract_sources.extend(c.claim.requires.iter().cloned());
        contract_sources.extend(c.claim.ensures.iter().cloned());
        if let Some(cf) = cf.as_ref() {
            if let Some((_, text)) = &cf.requires {
                contract_sources.push(text.clone());
            }
            if let Some((_, text)) = &cf.ensures {
                contract_sources.push(text.clone());
            }
        }
        for text in &contract_sources {
            for helper in surface::contract_helpers(text) {
                if !helpers.contains(&helper) {
                    helpers.push(helper);
                }
            }
        }
        for helper in helpers {
            let claimed = fn_claim_checks(&doc, &helper);
            items.push(contract_helper_item(&node_id, c.fn_name, &helper, claimed));
        }

        if c.claim.mode == Mode::Synth {
            derived_claimed.insert(c.fn_name.clone());
            let hash = scanned
                .derived
                .iter()
                .find(|d| d.item == *c.fn_name)
                .and_then(|d| d.spec_hash.clone());
            items.push(derived_item(&node_id, c.fn_name, hash.as_deref(), None));
        }
    });

    // A `#[ply::derived]` body whose claim does not say `mode: synth` --
    // §5.7's own drift case, reported as the trust surface it is.
    for d in &scanned.derived {
        if !derived_claimed.contains(&d.item) {
            items.push(derived_item(
                &d.item,
                &d.item,
                d.spec_hash.as_deref(),
                Some(&format!("{}:{}", d.file, d.line)),
            ));
        }
    }

    for a in shared::assumed_contracts(crate_dir, &doc, &local_anchors) {
        items.push(assumed_contract_item(&a));
    }

    for e in &scanned.escapes {
        items.push(escape_item(e));
    }

    items.sort_by_key(|i| {
        (
            AuditReport::TIERS
                .iter()
                .position(|t| *t == i.kind)
                .unwrap_or(usize::MAX),
            i.node_id.clone(),
            i.subject.clone(),
        )
    });

    let assumed = items
        .iter()
        .filter(|i| i.kind == "assumed_contract")
        .count();
    let coverage = read_coverage(&document, claims, doc.components.len(), assumed, &scanned);

    Ok(AuditReport {
        envelope: Envelope {
            command: "audit".into(),
            ply_version: PLY_VERSION.into(),
            root: workspace_node(&doc),
            diagnostics: vec![],
            coverage: Some(coverage),
            trust_surface: Some(items),
            open_items: None,
            not_carried_forward: vec![],
        },
        document,
    })
}

/// What the document asks for on a fn named by name alone, for a helper
/// that may or may not be claimed anywhere: `None` when no entry names it,
/// otherwise the checks that govern it and the component they were written
/// on when they were not written on the entry itself.
///
/// Resolved through the one shared §5.1 resolution (`FnClaimRef::
/// governing_checks`), so a helper that takes its checks from its component
/// is not reported as one nothing checks.
fn fn_claim_checks(
    doc: &ply_core::model::Document,
    name: &str,
) -> Option<(Vec<String>, Option<String>)> {
    let mut found = None;
    walk_fn_claims(doc, |c| {
        if c.fn_name == name {
            let governing = c.governing_checks();
            found = Some((
                governing
                    .as_ref()
                    .map(|g| g.checks.to_vec())
                    .unwrap_or_default(),
                governing
                    .as_ref()
                    .and_then(|g| g.from_component.map(str::to_string)),
            ));
        }
    });
    found
}

fn assumed_contract_item(a: &shared::AssumedContract) -> TrustItem {
    let (caller, callee, contract) = (&a.caller_fn, &a.callee, &a.contract);
    let discharge = discharge_advice(a);
    TrustItem {
        kind: "assumed_contract".into(),
        subject: callee.clone(),
        node_id: a.caller_node_id.clone(),
        statuses: vec!["owed-evidence".into()],
        where_: Some(a.where_text.clone()),
        detail: format!(
            "`{caller}`'s proof never reads `{callee}`'s code. Ply replaces the call with the \
             promise `ply.yaml` declares for that function — {contract} — and proves `{caller}` \
             against the promise instead of the body, which is why `{caller}`'s verdict reads \
             `conditional`. If the promise is wrong, the verdict is wrong with it. Nothing has run \
             `{callee}` against that promise yet, and that is what `owed-evidence` means here. \
             {discharge} (§5.5)"
        ),
    }
}

/// How to settle this assumption — said so that it can be acted on from
/// where the reader is standing.
///
/// `cargo ply verify` checks one crate at a time. When the callee's entry
/// belongs to another package, a `checks:` on it is read for its promise
/// and declined for its checks (`W0303`), so advice that stops at "add a
/// check to its entry" is advice this tool will refuse: the reader follows
/// it, watches it be declined, and is no further forward. Both the package
/// to run it in and the route that needs no second crate go on the line.
fn discharge_advice(a: &shared::AssumedContract) -> String {
    let (caller, callee) = (&a.caller_fn, &a.callee);
    // Where the check the callee already has was written. A default
    // declared on its component governs it exactly as a line on the entry
    // would (§5.1), but telling a reader to look at "its entry" for a line
    // that is one level up sends them hunting.
    let asks = |check: &String| match a.callee_checks_from.as_deref() {
        None => format!("Its `ply.yaml` entry already asks for `{check}`"),
        Some(from) => format!(
            "Its `ply.yaml` entry already asks for `{check}` — the default the component \
             `{from}` sets for everything inside it"
        ),
    };
    match (a.callee_checks.first(), a.callee_anchor.as_deref()) {
        (Some(check), None) => format!(
            "{}, which runs the real body against the promise: `cargo ply verify` is what \
             settles it.",
            asks(check)
        ),
        (Some(check), Some(anchor)) => format!(
            "{}, which runs the real body against the promise — but only where that function \
             lives: run `cargo ply verify` inside the `{anchor}` crate. This run checks one \
             crate at a time, so from here that entry's promise is read and its checks are \
             skipped.",
            asks(check)
        ),
        (None, None) => format!(
            "To settle it, add `checks: [fuzz(256)]` to its `ply.yaml` entry — fuzzing crosses a \
             legacy boundary by simply calling the code, so it tests the promise against the real \
             `{callee}`."
        ),
        (None, Some(anchor)) => format!(
            "To settle it, add `checks: [fuzz(256)]` to its `ply.yaml` entry and run `cargo ply \
             verify` inside the `{anchor}` crate, which is where that function lives — fuzzing \
             crosses a legacy boundary by simply calling the code, so it tests the promise \
             against the real `{callee}`. Adding the check changes nothing in this crate: \
             `cargo ply verify` checks one crate at a time and will decline to run it from here. \
             If you would rather not leave this crate, pass what `{callee}` returns into \
             `{caller}` as a parameter instead: the value becomes the caller's own data and there \
             is no promise left to owe."
        ),
    }
}

fn environmental_assumption_item(
    node_id: &str,
    fn_name: &str,
    clause: &str,
    entry: &[String],
) -> TrustItem {
    let parties = entry
        .iter()
        .map(|e| format!("`{e}`"))
        .collect::<Vec<_>>()
        .join(", ");
    TrustItem {
        kind: "environmental_assumption".into(),
        subject: clause.into(),
        node_id: node_id.into(),
        statuses: vec![],
        where_: None,
        detail: format!(
            "`{fn_name}` is declared as an entry point for {parties} — an outside party Ply never \
             verifies, because there is no code here to read. Its precondition `{clause}` is \
             therefore an assumption about the world rather than something a caller establishes: \
             the code that satisfies it is on the other side of the boundary, where no engine of \
             Ply's can reach. This is trust surface, not an open item: writing the assumption down \
             is the honest move, and deleting it would only hide it. (§5.1)"
        ),
    }
}

fn trusted_claim_item(node_id: &str, fn_name: &str, claim: &str, evidence: &str) -> TrustItem {
    TrustItem {
        kind: "trusted_claim".into(),
        subject: claim.into(),
        node_id: node_id.into(),
        statuses: vec!["staleness-unknown".into()],
        where_: None,
        detail: format!(
            "`{fn_name}` carries a claim no engine checked: “{claim}”, attested by a human and \
             evidenced by {evidence}. §5.4d records it so a node whose real correctness argument \
             lives outside Ply does not render indistinguishably green beside one Ply proved. \
             Whether the code it vouches for has changed since somebody signed it off is not known \
             in this run — see what this command could not look at, below. Re-attestation is a \
             human act, and nothing in Ply clears it. (§5.4d)"
        ),
    }
}

fn contract_helper_item(
    node_id: &str,
    caller: &str,
    helper: &str,
    claimed: Option<(Vec<String>, Option<String>)>,
) -> TrustItem {
    let standing = match claimed {
        None => {
            format!("`{helper}` carries no claim of its own in `ply.yaml`, so nothing checks it.")
        }
        Some((checks, None)) if checks.is_empty() => format!(
            "`{helper}` has a `ply.yaml` entry that asks for no checks, so nothing checks it."
        ),
        Some((checks, Some(from))) if checks.is_empty() => format!(
            "`{helper}` writes no checks of its own, and the component `{from}` declares an empty \
             list as the default for everything inside it, so nothing checks it."
        ),
        Some((checks, None)) => format!(
            "`{helper}` carries its own claim (`checks: [{}]`); whether that check passes is not \
             something this command knows.",
            checks.join(", ")
        ),
        Some((checks, Some(from))) => format!(
            "`{helper}` is checked with `{}`, which the component `{from}` declares as the \
             default for everything inside it; whether that check passes is not something this \
             command knows.",
            checks.join(", ")
        ),
    };
    TrustItem {
        kind: "contract_helper".into(),
        subject: helper.into(),
        node_id: node_id.into(),
        statuses: vec![],
        where_: None,
        detail: format!(
            "`{caller}`'s contract calls `{helper}(…)`. A contract is only as true as the helpers \
             it calls: if `{helper}` is wrong or panics, every verdict built on that contract \
             inherits it — §5.4a calls a helper used in a contract a trust surface, not a free \
             pass. {standing} (§5.4a)"
        ),
    }
}

fn escape_item(e: &ply_core::surface::Escape) -> TrustItem {
    let reason = match &e.reason {
        Some(r) => format!(", with the reason “{r}”"),
        None => ", with no reason written down".to_string(),
    };
    TrustItem {
        kind: "profile_escape".into(),
        subject: e.suppressed.clone(),
        node_id: e.item.clone(),
        statuses: vec![],
        where_: Some(format!("{}:{}", e.file, e.line)),
        detail: format!(
            "`{}` switches off `{}` for itself{reason}. Ply will not report that rule against this \
             item. The escape is listed here because an exemption granted once is easy to forget, \
             and the next reader deserves to see it beside everything else this codebase takes on \
             trust. (§5.3)",
            e.item, e.suppressed
        ),
    }
}

fn derived_item(
    node_id: &str,
    fn_name: &str,
    spec_hash: Option<&str>,
    where_: Option<&str>,
) -> TrustItem {
    let hash = match spec_hash {
        Some(h) => format!(
            " Recorded spec hash: `{h}` — when somebody hand-edits the body the hash stops \
             matching, and §5.7 turns the fn back into an ordinary `mode: check` claim with a \
             `W0531` warning."
        ),
        None => String::new(),
    };
    TrustItem {
        kind: "derived_fn".into(),
        subject: fn_name.into(),
        node_id: node_id.into(),
        statuses: vec![],
        where_: where_.map(|w| w.to_string()),
        detail: format!(
            "A model wrote this body against its spec, and a model is not a witness to its own \
             work — `{fn_name}` is on this list because the thing that wrote the code and the \
             thing the code is checked against came from the same place. It is checked like any \
             other claim.{hash} (§5.7)"
        ),
    }
}

fn unread_coverage() -> Coverage {
    Coverage {
        checked: vec![
            Tier {
                tier: "document".into(),
                detail: "NOT REACHED. The document did not pass the schema, so there was nothing \
                         well-formed to read a trust surface out of."
                    .into(),
            },
            Tier {
                tier: "call graph".into(),
                detail: "NOT REACHED. Same reason.".into(),
            },
            Tier {
                tier: "source".into(),
                detail: "NOT REACHED. Same reason.".into(),
            },
        ],
        not_checked: gaps(),
    }
}

fn read_coverage(
    document: &str,
    claims: usize,
    components: usize,
    assumed: usize,
    scanned: &SourceSurface,
) -> Coverage {
    Coverage {
        checked: vec![
            Tier {
                tier: "document".into(),
                detail: format!(
                    "{} across {}, read from {document}. Trusted claims, environmental \
                     assumptions and `mode: synth` claims come from here.",
                    plural(claims, "fn claim"),
                    plural(components, "top-level component"),
                ),
            },
            Tier {
                tier: "call graph".into(),
                detail: format!(
                    "Every call site written in a `bounded` claim's own body, classified the same \
                     way `cargo ply verify` classifies it. {assumed} of them {} on a contract \
                     declared for a callee Ply does not read.",
                    if assumed == 1 { "stands" } else { "stand" },
                ),
            },
            Tier {
                tier: "source".into(),
                detail: format!(
                    "Every `.rs` file under `src/`, read for `#[ply::allow]` escapes ({}), \
                     `#[ply::derived]` bodies ({}), and the helper functions contracts call.",
                    scanned.escapes.len(),
                    scanned.derived.len()
                ),
            },
        ],
        not_checked: gaps(),
    }
}

/// English, so a report about one thing does not read as a report about a
/// list of them.
fn plural(n: usize, noun: &str) -> String {
    if n == 1 {
        format!("1 {noun}")
    } else {
        format!("{n} {noun}s")
    }
}

fn gaps() -> Vec<Tier> {
    vec![
        Tier {
            tier: "attestation coverage".into(),
            detail: ATTESTATION_GAP.into(),
        },
        Tier {
            tier: "assumption discharge".into(),
            detail: DISCHARGE_GAP.into(),
        },
        Tier {
            tier: "helper evidence".into(),
            detail: HELPER_GAP.into(),
        },
        Tier {
            tier: "unreadable call sites".into(),
            detail: CALL_SITE_GAP.into(),
        },
        Tier {
            tier: "architecture bans".into(),
            detail: ARCHITECTURE_GAP.into(),
        },
    ]
}

/// The human surface. Same order as `check`: what ran, then what it found,
/// then what was NOT looked at — the part a short list most needs to carry.
pub fn print_human(report: &AuditReport) {
    println!("cargo ply audit — {}", report.document);
    println!();
    let cov = report
        .envelope
        .coverage
        .as_ref()
        .expect("audit sets coverage");
    for tier in &cov.checked {
        println!("  {:<12}{}", tier.tier, wrap(&tier.detail, 14));
    }
    println!();

    match report.envelope.trust_surface.as_ref() {
        None => println!("  The trust surface was not read (see above)."),
        Some(items) if items.is_empty() => println!("{}", wrap(EMPTY_SURFACE, 0)),
        Some(items) => {
            println!(
                "The trust surface — what this codebase's evidence rests on, and Ply does not check:"
            );
            for kind in AuditReport::TIERS {
                let tier: Vec<&TrustItem> = items.iter().filter(|i| i.kind == kind).collect();
                if tier.is_empty() {
                    continue;
                }
                println!();
                println!("  {} ({})", tier_heading(kind), tier.len());
                for item in tier {
                    println!("    {}", item_line(item));
                    println!("      {}", wrap(&item.detail, 6));
                }
            }
        }
    }
    println!();
    println!("What this command did NOT look at:");
    for tier in &cov.not_checked {
        println!("  {:<26}{}", tier.tier, wrap(&tier.detail, 28));
    }
    println!();
    println!("{}", wrap(NO_VERDICTS, 0));
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A crate directory: `src/lib.rs`, `ply.yaml`, a manifest. `audit`
    /// reads no more than that, and compiles nothing.
    fn crate_with(lib: &str, yaml: &str) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("src")).unwrap();
        std::fs::write(dir.path().join("src/lib.rs"), lib).unwrap();
        std::fs::write(dir.path().join("ply.yaml"), yaml).unwrap();
        std::fs::write(
            dir.path().join("Cargo.toml"),
            "[package]\nname = \"demo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
        )
        .unwrap();
        dir
    }

    /// §5.5's second branch, as the fixture `boundarycontract` writes it:
    /// a legacy callee with no contract of its own, a contract declared for
    /// it in ply.yaml, and a caller whose `bounded` proof rests on that.
    const BOUNDARY_LIB: &str = "pub fn legacy_rate(tier: u8) -> u32 { if tier == 0 { 150 } else { 90 } }\n\
         #[ply::requires(amount <= 100)]\n\
         #[ply::ensures(|result| *result <= amount)]\n\
         pub fn tiered_fee(amount: u32, tier: u8) -> u32 { legacy_rate(tier).min(amount) }\n";
    const BOUNDARY_YAML: &str = "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    fns:\n      legacy_rate:\n        ensures:\n          - \"|result| *result <= 10_000\"\n      tiered_fee:\n        checks: [bounded(2)]\n";

    fn item_kinds(report: &AuditReport) -> Vec<&str> {
        report
            .envelope
            .trust_surface
            .as_ref()
            .unwrap()
            .iter()
            .map(|i| i.kind.as_str())
            .collect()
    }

    fn only(report: &AuditReport, kind: &str) -> ply_core::diag::TrustItem {
        let found: Vec<_> = report
            .envelope
            .trust_surface
            .as_ref()
            .unwrap()
            .iter()
            .filter(|i| i.kind == kind)
            .cloned()
            .collect();
        assert_eq!(found.len(), 1, "{:#?}", report.envelope.trust_surface);
        found.into_iter().next().unwrap()
    }

    /// The case this whole command exists to surface (§5.5, honesty
    /// condition 3): the assumption is auditable, it names the callee, the
    /// promise and the caller resting on it, and it carries `owed-evidence`
    /// — which until now was recorded nowhere and displayed nowhere.
    #[test]
    fn an_assumed_contract_names_the_callee_the_promise_and_the_caller_that_rests_on_it() {
        let dir = crate_with(BOUNDARY_LIB, BOUNDARY_YAML);
        let report = audit_crate(dir.path()).unwrap();
        let item = only(&report, "assumed_contract");
        assert_eq!(item.subject, "legacy_rate");
        assert_eq!(item.node_id, "demo::tiered_fee");
        assert_eq!(item.statuses, vec!["owed-evidence".to_string()]);
        assert!(
            item.detail.contains("ensures |result| *result <= 10_000"),
            "the promise itself has to be on the line, or a reader cannot judge it: {}",
            item.detail
        );
        assert!(
            item.detail.contains("`tiered_fee`") && item.detail.contains("`legacy_rate`"),
            "{}",
            item.detail
        );
        assert!(
            item.detail
                .contains("Nothing has run `legacy_rate` against that promise yet"),
            "{}",
            item.detail
        );
        assert!(
            item.detail
                .contains("add `checks: [fuzz(256)]` to its `ply.yaml` entry"),
            "an owed item that does not say how to discharge it is a nag, not a worklist: {}",
            item.detail
        );
    }

    /// §5.5's second branch across a crate boundary -- which is the case
    /// it exists for: the callee is two-year-old code in another package.
    const CROSS_CRATE_LIB: &str = "#[ply::requires(amount <= 100)]\n\
         #[ply::ensures(|result| *result <= amount)]\n\
         pub fn tiered_fee(amount: u32, tier: u8) -> u32 { ledger::fees::bps_for_tier(tier).min(amount) }\n";
    const CROSS_CRATE_YAML: &str = "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    fns:\n      tiered_fee:\n        checks: [bounded(2)]\n  ledger:\n    anchor: ledger\n    fns:\n      fees::bps_for_tier:\n        ensures:\n          - \"|result| *result <= 10_000\"\n";

    /// The two-crate layout §5.5's boundary case actually has: the crate
    /// being audited, and a path dependency holding the legacy callee.
    /// Returns the tempdir (kept alive by the caller) and the crate to run
    /// in.
    fn crate_with_legacy_dependency(yaml: &str) -> (tempfile::TempDir, std::path::PathBuf) {
        let root = tempfile::tempdir().unwrap();
        let ledger = root.path().join("ledger");
        std::fs::create_dir_all(ledger.join("src")).unwrap();
        std::fs::write(
            ledger.join("src/lib.rs"),
            "pub mod fees {\n    pub fn bps_for_tier(tier: u8) -> u32 { if tier == 0 { 150 } else { 90 } }\n}\n",
        )
        .unwrap();
        std::fs::write(
            ledger.join("Cargo.toml"),
            "[package]\nname = \"ledger\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
        )
        .unwrap();

        let demo = root.path().join("demo");
        std::fs::create_dir_all(demo.join("src")).unwrap();
        std::fs::write(demo.join("src/lib.rs"), CROSS_CRATE_LIB).unwrap();
        std::fs::write(demo.join("ply.yaml"), yaml).unwrap();
        std::fs::write(
            demo.join("Cargo.toml"),
            "[package]\nname = \"demo\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n\
             [dependencies]\nledger = { path = \"../ledger\" }\n",
        )
        .unwrap();
        (root, demo)
    }

    /// Two commands, each right on its own, sending a reader in a circle:
    /// this one says "add a check to that function's entry", and `verify`,
    /// run where the reader is standing, then refuses to run it because it
    /// checks one crate at a time (`W0303`). Advice a user cannot act on
    /// from where they are is worse than no advice: they follow it, watch
    /// it be declined, and learn nothing about what to do instead.
    #[test]
    fn advice_for_a_callee_in_another_package_says_where_that_advice_has_to_be_run() {
        let (_root, demo) = crate_with_legacy_dependency(CROSS_CRATE_YAML);
        let report = audit_crate(&demo).unwrap();
        let item = only(&report, "assumed_contract");
        assert_eq!(item.subject, "ledger::fees::bps_for_tier");
        assert!(
            item.detail
                .contains("run `cargo ply verify` inside the `ledger` crate"),
            "the advice has to name the package the suggested check would have to be run in, or \
             it sends the reader to a command that will decline it: {}",
            item.detail
        );
        assert!(
            item.detail.contains(
                "pass what `ledger::fees::bps_for_tier` returns into `tiered_fee` as a parameter"
            ),
            "and it should offer the route that needs no second crate at all: {}",
            item.detail
        );

        // The same crate boundary, with the check already written down. It
        // still does not run from here, so saying "`cargo ply verify` is
        // what settles it" would be the same circle one step further along.
        let already = CROSS_CRATE_YAML.replace(
            "      fees::bps_for_tier:\n        ensures:",
            "      fees::bps_for_tier:\n        checks: [fuzz(256)]\n        ensures:",
        );
        let (_root2, demo2) = crate_with_legacy_dependency(&already);
        let report2 = audit_crate(&demo2).unwrap();
        let item2 = only(&report2, "assumed_contract");
        assert!(
            item2
                .detail
                .contains("run `cargo ply verify` inside the `ledger` crate"),
            "a check already declared for a function in another package still only runs where \
             that function lives: {}",
            item2.detail
        );
    }

    /// The same assumption, on a callee whose entry already asks for the
    /// cheap check that would discharge it. The advice must change with the
    /// facts: telling a user to add a check they already added is how a
    /// listing loses its reader.
    #[test]
    fn an_assumed_contract_whose_callee_already_declares_a_check_says_to_run_verify_instead() {
        let yaml = BOUNDARY_YAML.replace(
            "      legacy_rate:\n        ensures:",
            "      legacy_rate:\n        checks: [fuzz(256)]\n        ensures:",
        );
        let dir = crate_with(BOUNDARY_LIB, &yaml);
        let report = audit_crate(dir.path()).unwrap();
        let item = only(&report, "assumed_contract");
        assert!(
            item.detail.contains(
                "Its `ply.yaml` entry already asks for `fuzz(256)`, which runs the real body \
                 against the promise: `cargo ply verify` is what settles it"
            ),
            "{}",
            item.detail
        );
    }

    /// §5.1: a component's `checks:` is the default for every fn inside
    /// it, and a trust listing has to read it through the same resolution
    /// `check` and `verify` use. This document asks for `fuzz(64)` on
    /// everything in `demo`; fuzzing crosses a legacy boundary by calling
    /// the real code (§5.5), so `tiered_fee` assumes nothing about
    /// `legacy_rate` and there is nothing here to list. Reading the fn's
    /// own (absent) list instead put the shape-aware `bounded(2)` back and
    /// printed an assumption `verify` never makes.
    #[test]
    fn a_component_default_that_asks_for_fuzzing_leaves_nothing_assumed() {
        let yaml = "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    checks: [fuzz(64)]\n    fns:\n      legacy_rate:\n        checks: []\n        ensures:\n          - \"|result| *result <= 10_000\"\n      tiered_fee: {}\n";
        let dir = crate_with(BOUNDARY_LIB, yaml);
        let report = audit_crate(dir.path()).unwrap();
        assert!(
            !item_kinds(&report).contains(&"assumed_contract"),
            "`tiered_fee` inherits `fuzz(64)` from its component, and fuzzing runs the real \
             `legacy_rate` -- nothing is assumed here, so nothing may be listed as assumed: {:#?}",
            report.envelope.trust_surface
        );
    }

    /// The same resolution's other rule, reaching these two commands for
    /// the first time: **an empty list is a list** (§5.4c). A caller that
    /// writes `checks: []` is checked by nothing, so it proves nothing, so
    /// it assumes nothing — and there is no trust surface to list. Reading
    /// the list for emptiness rather than for presence put the shape-aware
    /// `bounded(2)` back and listed the assumption that proof would have
    /// made.
    #[test]
    fn a_caller_that_asks_for_no_checks_at_all_leaves_nothing_assumed() {
        let yaml = BOUNDARY_YAML.replace(
            "      tiered_fee:\n        checks: [bounded(2)]\n",
            "      tiered_fee:\n        checks: []\n",
        );
        let dir = crate_with(BOUNDARY_LIB, &yaml);
        let report = audit_crate(dir.path()).unwrap();
        assert!(
            !item_kinds(&report).contains(&"assumed_contract"),
            "nothing checks `tiered_fee`, so nothing of its rests on `legacy_rate`'s promise: \
             {:#?}",
            report.envelope.trust_surface
        );
    }

    /// The same resolution the other way round, and one level down: the
    /// helper a contract calls writes no `checks:` of its own and sits in a
    /// nested component, so what runs against it is the default declared
    /// above. Reading only its own line said "nothing checks it" about a fn
    /// this document does check.
    #[test]
    fn a_helper_that_inherits_its_checks_is_not_reported_as_unchecked() {
        let dir = crate_with(
            "pub fn bps_ok(bps: u32) -> bool { bps <= 10_000 }\n\
             #[ply::requires(bps_ok(bps))]\n\
             pub fn fee(bps: u32) -> u32 { bps }\n",
            "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    checks: [test]\n    fns:\n      fee: {}\n    components:\n      helpers:\n        anchor: demo\n        fns:\n          bps_ok: {}\n",
        );
        let report = audit_crate(dir.path()).unwrap();
        let item = only(&report, "contract_helper");
        assert!(
            item.detail.contains(
                "`bps_ok` is checked with `test`, which the component `demo` declares as the \
                 default for everything inside it"
            ),
            "a helper that inherits its checks is checked, and saying otherwise overstates what \
             this contract rests on: {}",
            item.detail
        );
    }

    /// A fn's own `checks:` still wins entirely over the default above it,
    /// and the advice for settling a promise has to point at the line that
    /// carries the check: "its entry already asks for `fuzz(256)`" sends a
    /// reader to a line that is one level up from where they will look.
    #[test]
    fn advice_says_where_a_callee_takes_its_check_from_when_it_is_not_its_own_line() {
        let yaml = "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    checks: [fuzz(256)]\n    fns:\n      legacy_rate:\n        ensures:\n          - \"|result| *result <= 10_000\"\n      tiered_fee:\n        checks: [bounded(2)]\n";
        let dir = crate_with(BOUNDARY_LIB, yaml);
        let report = audit_crate(dir.path()).unwrap();
        let item = only(&report, "assumed_contract");
        assert!(
            item.detail.contains(
                "Its `ply.yaml` entry already asks for `fuzz(256)` — the default the component \
                 `demo` sets for everything inside it, which runs the real body against the \
                 promise: `cargo ply verify` is what settles it."
            ),
            "{}",
            item.detail
        );
    }

    /// An inherited *empty* default: the component says "check nothing" for
    /// everything inside it (§5.4c). Nothing checks the helper, which is
    /// what the old sentence said — but the `checks:` line a reader would
    /// go looking for is on the component, not on the entry, so the
    /// sentence has to say which one it is.
    #[test]
    fn a_helper_under_an_empty_component_default_names_the_component_that_declared_it() {
        let dir = crate_with(
            "pub fn bps_ok(bps: u32) -> bool { bps <= 10_000 }\n\
             #[ply::requires(bps_ok(bps))]\n\
             pub fn fee(bps: u32) -> u32 { bps }\n",
            "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    checks: []\n    fns:\n      fee: {}\n      bps_ok: {}\n",
        );
        let report = audit_crate(dir.path()).unwrap();
        let item = only(&report, "contract_helper");
        assert!(
            item.detail.contains(
                "`bps_ok` writes no checks of its own, and the component `demo` declares an empty \
                 list as the default for everything inside it, so nothing checks it."
            ),
            "{}",
            item.detail
        );
    }

    /// §5.4d: a trusted claim is a human's word, listed with the evidence
    /// they cited. Whether it still covers the item is the part Ply cannot
    /// supply yet,
    /// and saying "not known" is the difference between an honest list and
    /// one that implies every attestation is current.
    #[test]
    fn a_trusted_claim_is_listed_with_its_evidence_and_says_staleness_is_unknown() {
        let dir = crate_with(
            "pub fn quote() -> u32 { 1 }\n",
            "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    fns:\n      quote:\n        checks: [test]\n        trusted:\n          - { claim: \"cross-thread safety\", evidence: \"loom test tests/loom_quote.rs\" }\n",
        );
        let report = audit_crate(dir.path()).unwrap();
        let item = only(&report, "trusted_claim");
        assert_eq!(item.subject, "cross-thread safety");
        assert_eq!(item.node_id, "demo::quote");
        assert_eq!(item.statuses, vec!["staleness-unknown".to_string()]);
        assert!(
            item.detail.contains("loom test tests/loom_quote.rs"),
            "{}",
            item.detail
        );
        assert!(
            item.detail.contains(
                "Whether the code it vouches for has changed since somebody signed it off is \
                 not known in this run"
            ),
            "{}",
            item.detail
        );
    }

    /// §5.4a: "A `#[ply::pure]` helper called from any contract is a trust
    /// surface, not a free pass." The contract is only as true as what it
    /// calls.
    #[test]
    fn a_helper_called_from_a_contract_is_on_the_trust_surface() {
        let dir = crate_with(
            "pub fn bps_ok(bps: u32) -> bool { bps <= 10_000 }\n\
             #[ply::requires(bps_ok(bps))]\n\
             pub fn fee(bps: u32) -> u32 { bps }\n",
            "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    fns:\n      fee:\n        checks: [test]\n",
        );
        let report = audit_crate(dir.path()).unwrap();
        let item = only(&report, "contract_helper");
        assert_eq!(item.subject, "bps_ok");
        assert_eq!(item.node_id, "demo::fee");
        assert!(
            item.detail.contains(
                "if `bps_ok` is wrong or panics, every verdict built on that contract inherits it"
            ),
            "{}",
            item.detail
        );
        assert!(
            item.detail.contains(
                "`bps_ok` carries no claim of its own in `ply.yaml`, so nothing checks it"
            ),
            "{}",
            item.detail
        );
    }

    /// §5.3's per-item escape, and §5.1's `entry:` — one is an exemption
    /// somebody granted, the other an assumption about the world outside.
    /// Both are permanent trust surface; neither is owed.
    #[test]
    fn an_escape_and_an_environmental_assumption_are_listed_and_neither_is_owed() {
        let dir = crate_with(
            "#[ply::allow(no_panics, reason = \"bounds are checked by the caller\")]\n\
             pub fn fast_path(i: usize) -> u32 { [1, 2][i] }\n\
             #[ply::requires(tick > 0)]\n\
             pub fn quote(tick: u32) -> u32 { tick }\n",
            "ply: 1\nexternals:\n  venue:\n    note: \"the exchange: accepts orders, returns fills\"\ncomponents:\n  demo:\n    anchor: demo\n    fns:\n      quote:\n        checks: [test]\n        requires:\n          - \"tick > 0\"\n        entry: [venue]\n",
        );
        let report = audit_crate(dir.path()).unwrap();

        let escape = only(&report, "profile_escape");
        assert_eq!(escape.subject, "no_panics");
        assert_eq!(escape.node_id, "fast_path");
        assert!(
            escape.detail.contains("bounds are checked by the caller"),
            "{}",
            escape.detail
        );

        let env = only(&report, "environmental_assumption");
        assert_eq!(env.subject, "tick > 0");
        assert_eq!(env.node_id, "demo::quote");
        // Not "nothing inside this codebase calls `quote`" -- §5.1 gives
        // that as the reason for the rule, but `audit` does not walk the
        // whole call graph looking for callers, so stating it as a fact
        // about this crate would be a claim this command never checked.
        assert!(
            env.detail.contains(
                "the code that satisfies it is on the other side of the boundary, where no \
                 engine of Ply's can reach"
            ),
            "{}",
            env.detail
        );
        assert!(
            env.detail.contains(
                "This is trust surface, not an open item: writing the assumption down is the \
                 honest move, and deleting it would only hide it"
            ),
            "§5.1 is explicit that an environmental assumption is never counted as owed: {}",
            env.detail
        );
        for item in report.envelope.trust_surface.as_ref().unwrap() {
            if item.kind == "profile_escape" || item.kind == "environmental_assumption" {
                assert!(
                    !item.statuses.iter().any(|s| s == "owed-evidence"),
                    "{item:#?}"
                );
            }
        }
    }

    /// One clause, written in both places a contract can live, is one
    /// assumption. The two spellings do not match textually — the inline
    /// attribute comes back token-spaced — and comparing the raw strings
    /// listed it twice, which is a trust surface overstating itself. Found
    /// by reading the output, not by a failing assertion.
    #[test]
    fn a_clause_written_in_both_places_is_one_assumption_not_two() {
        let dir = crate_with(
            "pub fn bps_ok(bps: u32) -> bool { bps <= 10_000 }\n\
             #[ply::requires(bps_ok(bps))]\n\
             pub fn fee(bps: u32) -> u32 { bps }\n",
            "ply: 1\nexternals:\n  venue:\n    note: \"the exchange: accepts orders, returns fills\"\ncomponents:\n  demo:\n    anchor: demo\n    fns:\n      fee:\n        checks: [test]\n        requires:\n          - \"bps_ok(bps)\"\n        entry: [venue]\n",
        );
        let report = audit_crate(dir.path()).unwrap();
        let item = only(&report, "environmental_assumption");
        assert_eq!(
            item.subject, "bps_ok(bps)",
            "the spelling that survives is the one the user typed in ply.yaml, not the \
             parser's token rendering"
        );
    }

    /// A promise nothing can rest on is not trust surface. When the callee
    /// returns nothing, Ply's codegen has no value to stand in for it with,
    /// so `verify` refuses the assumption (`W0512`) and the caller earns no
    /// evidence — nobody is trusting anything. Listing it here would say a
    /// verdict rests on a promise when no verdict does.
    #[test]
    fn a_promise_verify_cannot_use_is_not_on_the_trust_surface() {
        let dir = crate_with(
            "pub fn log_rate(tier: u8) {}\n\
             #[ply::requires(amount <= 100)]\n\
             #[ply::ensures(|result| *result <= amount)]\n\
             pub fn tiered_fee(amount: u32, tier: u8) -> u32 { log_rate(tier); amount }\n",
            "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    fns:\n      log_rate:\n        requires:\n          - \"tier < 4\"\n      tiered_fee:\n        checks: [bounded(2)]\n",
        );
        let report = audit_crate(dir.path()).unwrap();
        assert!(
            !item_kinds(&report).contains(&"assumed_contract"),
            "{:#?}",
            report.envelope.trust_surface
        );
    }

    /// §5.7: a body the model wrote, from ply.yaml's `mode: synth` and from
    /// the attribute `synth` leaves behind.
    #[test]
    fn a_derived_fn_is_listed_from_the_claim_and_from_the_attribute() {
        let dir = crate_with(
            "#[ply::derived(spec_hash = \"b3f9ac\")]\npub fn quote() -> u32 { 1 }\n",
            "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    fns:\n      quote:\n        checks: [test]\n        mode: synth\n",
        );
        let report = audit_crate(dir.path()).unwrap();
        let items: Vec<_> = report
            .envelope
            .trust_surface
            .as_ref()
            .unwrap()
            .iter()
            .filter(|i| i.kind == "derived_fn")
            .cloned()
            .collect();
        assert_eq!(items.len(), 1, "{items:#?}");
        assert_eq!(items[0].subject, "quote");
        assert!(
            items[0].detail.contains(
                "A model wrote this body against its spec, and a model is not a witness to its \
                 own work"
            ),
            "{}",
            items[0].detail
        );
        assert!(items[0].detail.contains("b3f9ac"), "{}", items[0].detail);
    }

    /// The tier order is fixed, so two runs of `audit` on a growing
    /// codebase read as the same document with more lines in it.
    #[test]
    fn the_surface_is_reported_in_one_fixed_tier_order() {
        let dir = crate_with(BOUNDARY_LIB, BOUNDARY_YAML);
        let report = audit_crate(dir.path()).unwrap();
        assert_eq!(item_kinds(&report), ["assumed_contract"]);
        assert_eq!(
            AuditReport::TIERS,
            [
                "assumed_contract",
                "environmental_assumption",
                "trusted_claim",
                "contract_helper",
                "profile_escape",
                "derived_fn",
            ]
        );
    }

    /// The one line a reader scans before deciding whether to read the
    /// paragraph under it. It has to say what is trusted, who is trusting
    /// it, where to look, and whether anything is owed — in that order, and
    /// in words, not in field names.
    #[test]
    fn one_surface_line_says_what_is_trusted_who_trusts_it_and_what_is_owed() {
        let dir = crate_with(BOUNDARY_LIB, BOUNDARY_YAML);
        let report = audit_crate(dir.path()).unwrap();
        let item = only(&report, "assumed_contract");
        assert_eq!(
            item_line(&item),
            "`legacy_rate` — assumed by `demo::tiered_fee` (at line 4, column 51)  [owed-evidence]"
        );
    }

    /// A trust surface is not a list of problems (§5.5: `conditional` "is
    /// the *normal* state of a legacy-extension codebase"). Exiting
    /// non-zero because a codebase has an assumption in it would push users
    /// to delete honest declarations, which is the one outcome this command
    /// must not cause.
    #[test]
    fn a_run_with_a_trust_surface_still_exits_zero() {
        let dir = crate_with(BOUNDARY_LIB, BOUNDARY_YAML);
        let report = audit_crate(dir.path()).unwrap();
        assert!(!report.envelope.trust_surface.as_ref().unwrap().is_empty());
        assert_eq!(report.exit_code(), 0);
    }

    /// The `check`-shaped honesty: what this command cannot see, in the
    /// same `coverage.not_checked` place, in exact words.
    #[test]
    fn the_report_names_everything_it_could_not_look_at() {
        let dir = crate_with(
            "pub fn quote() -> u32 { 1 }\n",
            "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n",
        );
        let report = audit_crate(dir.path()).unwrap();
        let cov = report.envelope.coverage.as_ref().unwrap();
        let names: Vec<&str> = cov.not_checked.iter().map(|t| t.tier.as_str()).collect();
        assert_eq!(
            names,
            [
                "attestation coverage",
                "assumption discharge",
                "helper evidence",
                "unreadable call sites",
                "architecture bans"
            ]
        );
        assert_eq!(cov.not_checked[0].detail, ATTESTATION_GAP);
        assert_eq!(cov.not_checked[1].detail, DISCHARGE_GAP);
        assert_eq!(cov.not_checked[2].detail, HELPER_GAP);
        assert_eq!(cov.not_checked[3].detail, CALL_SITE_GAP);
        assert_eq!(cov.not_checked[4].detail, ARCHITECTURE_GAP);
    }

    /// The tier lines are the first thing a reader sees, and they are
    /// sentences about this crate, not field dumps. Checked as exact
    /// strings because a count that reads "1 call sites" or a line that
    /// loses its number entirely still passes every structural test.
    #[test]
    fn the_tier_lines_count_in_english() {
        let dir = crate_with(BOUNDARY_LIB, BOUNDARY_YAML);
        let report = audit_crate(dir.path()).unwrap();
        let cov = report.envelope.coverage.as_ref().unwrap();
        assert_eq!(
            cov.checked[0].detail,
            format!(
                "2 fn claims across 1 top-level component, read from {}. Trusted claims, \
                 environmental assumptions and `mode: synth` claims come from here.",
                report.document
            )
        );
        assert_eq!(
            cov.checked[1].detail,
            "Every call site written in a `bounded` claim's own body, classified the same way \
             `cargo ply verify` classifies it. 1 of them stands on a contract declared for a \
             callee Ply does not read."
        );
    }

    /// An empty surface must read as "nothing is declared here", never as
    /// "everything is verified".
    #[test]
    fn a_codebase_with_no_trust_surface_says_so_in_words() {
        let dir = crate_with(
            "pub fn quote() -> u32 { 1 }\n",
            "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n",
        );
        let report = audit_crate(dir.path()).unwrap();
        assert!(report.envelope.trust_surface.as_ref().unwrap().is_empty());
        assert!(EMPTY_SURFACE.contains("Nothing in this crate rests on trust that Ply can see"));
        assert!(NO_VERDICTS.contains("runs no engines"));
    }

    /// §8's envelope, with `audit` in the command field, the trust surface
    /// as data, and a node tree that claims no evidence anywhere.
    #[test]
    fn the_envelope_is_the_section_8_shape_with_the_trust_surface_as_data() {
        let dir = crate_with(BOUNDARY_LIB, BOUNDARY_YAML);
        let report = audit_crate(dir.path()).unwrap();
        let json: serde_json::Value =
            serde_json::from_str(&report.envelope.to_json_pretty()).unwrap();
        assert_eq!(json["command"], "audit");
        assert_eq!(json["root"]["kind"], "workspace");
        assert_eq!(json["root"]["verdict"], "unclaimed");
        let surface = json["trust_surface"].as_array().unwrap();
        assert_eq!(surface[0]["kind"], "assumed_contract");
        assert_eq!(surface[0]["subject"], "legacy_rate");
        assert_eq!(surface[0]["node_id"], "demo::tiered_fee");
        assert_eq!(surface[0]["statuses"][0], "owed-evidence");
        assert!(surface[0]["detail"].is_string());
    }

    /// A document that does not pass the schema gets one honest answer, and
    /// the coverage block says the surface was never read rather than
    /// leaving a reader to assume it was empty.
    #[test]
    fn a_schema_violation_stops_before_the_surface_and_says_so() {
        let dir = crate_with(
            "pub fn quote() -> u32 { 1 }\n",
            "ply: 1\ncomponents:\n  demo:\n    anchor: demo\n    fns:\n      quote:\n        ensure: [\"x > 0\"]\n",
        );
        let report = audit_crate(dir.path()).unwrap();
        assert_eq!(report.envelope.diagnostics[0].code, "E0204");
        assert_eq!(report.exit_code(), 1);
        let cov = report.envelope.coverage.as_ref().unwrap();
        assert!(
            cov.checked[0].detail.starts_with("NOT REACHED."),
            "{}",
            cov.checked[0].detail
        );
    }

    /// No `ply.yaml` is a tool error, not an empty trust surface: an
    /// `audit` that reports "nothing to trust here" for a crate it never
    /// read would be the worst sentence this command could print.
    #[test]
    fn a_missing_document_is_a_tool_error_naming_the_path_it_looked_at() {
        let dir = tempfile::tempdir().unwrap();
        let err = audit_crate(dir.path()).unwrap_err().to_string();
        assert!(err.contains("could not read a ply.yaml at"), "{err}");
        assert!(err.contains("cargo ply audit"), "{err}");
    }
}
